AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TNBHookRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'TNBHookRole'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"